seed: 33
do_train: True
log_dir: logs
resume: False
resume_path: null
task_name: debug

video_feature_extractor: ${oc.load:configs/qwen3_vl/vision_config_8b.yaml}

projector:
  type: qformer # mlp | qformer
  num_token: 2
  num_attn_layers: 6
  num_attn_compress_layers: 6
  hidden_dim: 4096
  output_align_dim: 4096
  cross_attention_dim: 2048

wanva:
  model_path: ${oc.env:PRETRAINED_MODEL_PATH}/Wan-AI/Wan2.2-TI2V-5B-Diffusers/

data:
  fps: 24
  frames: 4
  num_workers: 32
  image_size: [256, 256]
  train_json_path: ./jsons/train_debug.json
  eval_json_path: ./jsons/eval_debug.json
