seed: 33
do_train: True
log_dir: logs
resume: False
resume_path: null
task_name: debug

action:
  num_layers: 6
  action_dim: 7
  chunk_size: 4

projector:
  type: qformer # mlp | qformer
  num_token: 2
  num_attn_layers: 6
  num_attn_compress_layers: 6
  num_attention_heads: 8
  hidden_dim: 4096
  output_align_dim: 4096
  cross_attention_dim: 2048
  patch_size: [1, 2, 2]

wanva:
  token_dropout: False
  guidance_scale: 1.0
  num_inference_steps: 20
  patch_size: [1, 2, 2]
  num_attention_heads: 24
  model_path: ${oc.env:PRETRAINED_MODEL_PATH}/Wan-AI/Wan2.2-TI2V-5B-Diffusers/

data:
  type: video # video | hdf5 | lerobot
  fps: 2
  frames: 5
  num_workers: 16
  image_size: [256, 256]
  train_json_path: ./jsons/train_debug.json
  eval_json_path: ./jsons/eval_debug.json

lora:
  enable: True
  r: 16
  lora_alpha: 32

train:
  dist: True
  epochs: 200
  num_iters: null
  eval_step: 20
  save_step: 20
  local_batch_size: 8
  eval_sample_num: 4
  learning_rate: 3e-5
  warmup_ratio: 0.01
  decay: 1e-3
  ckpt_save_dir: ckpts
  gradient_accumulate_steps: 2
